Prod[ Oc[0], Oc[0] ] :=  Oc[0]
Prod[ Oc[0], Oc[1] ] :=  Oc[1]
Prod[ Oc[0], Oc[2] ] :=  Oc[2]
Prod[ Oc[0], Oc[3] ] :=  Oc[3]
Prod[ Oc[0], Oc[4] ] :=  Oc[4]
Prod[ Oc[0], Oc[5] ] :=  Oc[5]
Prod[ Oc[0], Oc[6] ] :=  Oc[6]
Prod[ Oc[0], Oc[7] ] :=  Oc[7]

Prod[ Oc[1], Oc[0] ] :=  Oc[1]
Prod[ Oc[1], Oc[1] ] := -Oc[0]
Prod[ Oc[1], Oc[2] ] :=  Oc[3]
Prod[ Oc[1], Oc[3] ] := -Oc[2]
Prod[ Oc[1], Oc[4] ] :=  Oc[5]
Prod[ Oc[1], Oc[5] ] := -Oc[4]
Prod[ Oc[1], Oc[6] ] := -Oc[7]
Prod[ Oc[1], Oc[7] ] :=  Oc[6]

Prod[ Oc[2], Oc[0] ] :=  Oc[2]
Prod[ Oc[2], Oc[1] ] := -Oc[3]
Prod[ Oc[2], Oc[2] ] := -Oc[0]
Prod[ Oc[2], Oc[3] ] :=  Oc[1]
Prod[ Oc[2], Oc[4] ] :=  Oc[6]
Prod[ Oc[2], Oc[5] ] :=  Oc[7]
Prod[ Oc[2], Oc[6] ] := -Oc[4]
Prod[ Oc[2], Oc[7] ] := -Oc[5]

Prod[ Oc[3], Oc[0] ] :=  Oc[3]
Prod[ Oc[3], Oc[1] ] :=  Oc[2]
Prod[ Oc[3], Oc[2] ] := -Oc[1]
Prod[ Oc[3], Oc[3] ] := -Oc[0]
Prod[ Oc[3], Oc[4] ] :=  Oc[7]
Prod[ Oc[3], Oc[5] ] := -Oc[6]
Prod[ Oc[3], Oc[6] ] :=  Oc[5]
Prod[ Oc[3], Oc[7] ] := -Oc[4]

Prod[ Oc[4], Oc[0] ] :=  Oc[4]
Prod[ Oc[4], Oc[1] ] := -Oc[5]
Prod[ Oc[4], Oc[2] ] := -Oc[6]
Prod[ Oc[4], Oc[3] ] := -Oc[7]
Prod[ Oc[4], Oc[4] ] := -Oc[0]
Prod[ Oc[4], Oc[5] ] :=  Oc[1]
Prod[ Oc[4], Oc[6] ] :=  Oc[2]
Prod[ Oc[4], Oc[7] ] :=  Oc[3]

Prod[ Oc[5], Oc[0] ] :=  Oc[5]
Prod[ Oc[5], Oc[1] ] :=  Oc[4]
Prod[ Oc[5], Oc[2] ] := -Oc[7]
Prod[ Oc[5], Oc[3] ] :=  Oc[6]
Prod[ Oc[5], Oc[4] ] := -Oc[1]
Prod[ Oc[5], Oc[5] ] := -Oc[0]
Prod[ Oc[5], Oc[6] ] := -Oc[3]
Prod[ Oc[5], Oc[7] ] :=  Oc[2]

Prod[ Oc[6], Oc[0] ] :=  Oc[6]
Prod[ Oc[6], Oc[1] ] :=  Oc[7]
Prod[ Oc[6], Oc[2] ] :=  Oc[4]
Prod[ Oc[6], Oc[3] ] := -Oc[5]
Prod[ Oc[6], Oc[4] ] := -Oc[2]
Prod[ Oc[6], Oc[5] ] :=  Oc[3]
Prod[ Oc[6], Oc[6] ] := -Oc[0]
Prod[ Oc[6], Oc[7] ] := -Oc[1]

Prod[ Oc[7], Oc[0] ] :=  Oc[7]
Prod[ Oc[7], Oc[1] ] := -Oc[6]
Prod[ Oc[7], Oc[2] ] :=  Oc[5]
Prod[ Oc[7], Oc[3] ] :=  Oc[4]
Prod[ Oc[7], Oc[4] ] := -Oc[3]
Prod[ Oc[7], Oc[5] ] := -Oc[2]
Prod[ Oc[7], Oc[6] ] :=  Oc[1]
Prod[ Oc[7], Oc[7] ] := -Oc[0]

